### ISSUE TITLE
Erros with current minimum iOS target version

### ISSUE THREAD

**Issue by joaocolaco** [ajevans99/swift-json-schema#30]
Hi. I tried to use this package in a project for iOS 18 in Xcode 16, however I'm getting some errors:

"Runtime support for parameterized protocol types is only available in iOS 16.0.0 or newer"
and
"
Parameter packs in generic types are only available in iOS 17.0.0 or newer
"
If i'd change the minimum target of the package to iOS 17 from 13 the issues are cleared as expected.

I'm missing something or minimum target should be iOS 17?

Thanks and best regards,
João Colaço

**Comment by ajevans99** [comment]
Interesting. I didn't know that. I knew the minimum version was Swift 5.10 because of the parameter packs and generics.

I guess there must be changes to the runtime that require iOS 17? I can update the Package.swift
