### ISSUE TITLE
Choice of model within .xcdatamodeld

### ISSUE THREAD

**Issue by vdhamer** [ajevans99/swift-json-schema#54]
Would prefer inverse sort order (to match Xcode).
And choosing the top one, rather than "arbitrary" choice of .xcdatamodel in the middle.

Not very important, so only worth doing if it is an easy change ;-)

<img width="434" alt="Screenshot 2024-12-11 at 11 48 46" src="https://github.com/user-attachments/assets/b8e61bde-4acd-4843-ada4-9513a4feb854">

Screenshot shows .xcdatamodeld file that was generated with xcode's editor (and never overwritten by CoreData Model Editor 1.4.1 or an earlier version).

**Comment by ajevans99** [comment]
Hey there. Think you may have posted this issue in the wrong repo. I'm not sure what that is a screenshot of 😄

**Comment by vdhamer** [comment]
> Hey there. Think you may have posted this issue in the wrong repo. I'm not sure what that is a screenshot of 😄

Correct. I realized I didn't post it where it should have ended up, but couldn't find where I put it ;-)
